### PR TITLE
update all the versions to 3.0.0-beta1

### PR DESCRIPTION
**Pull request by shalehaha**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by shalehaha** [comment]
edge extension is adding a hyphen between `beta` and the beta number, like https://github.com/adobe/aepsdk-edge-ios/releases/tag/1.0.0-beta-1. Core doesn't use the hyphen. 
Which do you think is better? @sbenedicadb @emdobrin

**Review by sbenedicadb — APPROVED** [review]

**Comment by sbenedicadb** [comment]
i'd vote for no hyphen.

**Review by yangyansong-adbe — APPROVED** [review]

**Comment by sbenedicadb** [comment]
@shalehaha we need to update version in all the podspecs as well

**Comment by kevinlind** [comment]
I'd vote for including the hyphen. I believe that is more common in Android/Maven, however either form is acceptable for semantic versioning, https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions.
I would agree with keeping them consistent, however the Edge extension beta-1 is already released.

**Comment by shalehaha** [comment]
https://github.com/Alamofire/Alamofire/pull/2799. I don't think any customer would actually put our binaries into a staging/production app, however it'd better make sure if they do that, our SDK won't cause any trouble. So for the framework versions, we should follow the pattern '3.0.0.beta.1'

For the version in code and the pod version, we can follow the semver spec, so it will be `3.0.0-beta.1`.

@sbenedicadb @emdobrin @kevinlind  any objection?

**Review by sbenedicadb — APPROVED** [review]

**Pull request merged**
