### PR TITLE
Make it possible to override the loggingService

### PR DESCRIPTION
**Pull request by m0rk**
## Description

According to the [documentation](https://github.com/adobe/aepsdk-core-ios/tree/main/Documentation/Services#overriding-a-service) this should be possible, but the implementation was a get-only property.

## Related Issue

https://github.com/adobe/aepsdk-core-ios/issues/874

## Motivation and Context

First of all it is mentioned as an example in the documentation of the ServiceProvider but the main reason is that we have a use case for writing the logs somewhere else for automated testing purposes.

## How Has This Been Tested?

I wrote a unit test.

## Types of changes

I am not entirely sure how to categorise this. If we take the documentation as the source of truth it would be a bug, else it is a non-breaking new feature. 

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by cdhoffmann** [comment]
@m0rk Can you sign Adobe's CLA? I will merge it once you do. Thanks for the contribution!

**Comment by m0rk** [comment]
@cdhoffmann I am a bit confused now, according to the last comment on the related issue you did not want customers overriding it, was there a change of heart in this regard? 😄 If this is indeed the case I will get the CLA resolved as fast as possible.

PS: Sorry for the late reply, I was sick.

**Comment by cdhoffmann** [comment]
@m0rk I apologize for the confusion. Originally that was our stance, but we have recently made this same change in our Android SDK so it will line up now. Thanks again for your contribution!

**Comment by m0rk** [comment]
Hello @cdhoffmann, I finally got the CLA signed.

**Review by cdhoffmann — APPROVED** [review]

**Pull request merged**
